server:
  port: ${PORT:8080}

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      authentication-database: admin
      username: root
      password: example
      database: formalizacao
      #uri: mongodb://root:example@localhost:27017


api:
  client:
    address:
      url: http://localhost:9999/address

kafka:
  bootstrapAddress: localhost:9092
  grupo-id: formalizacao
  topic:
    offset:
      reset: earliest
    cpf-validated: tp-cpf-validated
    cpf-validation: tp-cpf-validation
    card-processing: tp-card-processing
    card-processed: tp-card-processed

