version: "3.1"
services:
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - formalizao-digital

  kafka:
    image: 'bitnami/kafka:latest'
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
    networks:
      - formalizao-digital

  mongo:
    image: mongo
    container_name: mongo-test
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      - formalizao-digital

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017
    networks:
      - formalizao-digital

  wiremock:
    image: wiremock/wiremock:latest
    container_name: wiremock-formalizacao
    ports:
      - "9999:8080"
    volumes:
      - ./wiremock/__files/:/home/wiremock/__files/
      - ./wiremock/mappings/:/home/wiremock/mappings/
    command:
      - -global-response-templating
      - --verbose
    networks:
      - formalizao-digital




networks:
  formalizao-digital:
    driver: bridge